<?xml version="1.0"?>
<robot name="humanoid" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="body_width" value="0.05" /> <!-- Square dimensions (width x width) of body_link1 -->
  <xacro:property name="body_height1" value="0.5" /> <!-- body_link1 -->
  <xacro:property name="height1" value="2" /> <!-- Link 1 -->
  <xacro:property name="height2" value="1" /> <!-- Link 2 -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <xacro:include filename="$(find humanoid-robot)/urdf/humanoid.gazebo.xacro" />
  <xacro:include filename="$(find humanoid-robot)/urdf/materials.xacro" />
   
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="body_link1"/>
  </joint>

  <!-- Base Link -->
  <link name="body_link1">
    <collision>
      <origin xyz="0 0 ${body_height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${body_width} ${body_width} ${body_height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${body_height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${body_width} ${body_width} ${body_height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${body_height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (body_width*body_width + body_height1*body_height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (body_height1*body_height1 + body_width*body_width)}" iyz="0.0"
	  izz="${mass / 12.0 * (body_width*body_width + body_width*body_width)}"/>
    </inertial>
  </link>
  <joint name="body_joint1" type="fixed">
    <parent link="body_link1"/>
    <child link="body_link2"/>
    <origin xyz="0 0 ${body_height1 + 0.05/2.0}" rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="body_link2">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.05 0.2 0.05"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.05 0.2 0.05"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (body_width*body_width + body_height1*body_height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (body_height1*body_height1 + body_width*body_width)}" iyz="0.0"
	  izz="${mass / 12.0 * (body_width*body_width + body_width*body_width)}"/>
    </inertial>
  </link>

  <joint name="left_shoulder_joint1" type="revolute">
    <parent link="body_link2"/>
    <child link="left_shoulder"/>
    <origin xyz="0 ${-0.1 -0.025} 0" rpy="0 ${3.141592/2} 0"/>
	<limit effort="300" velocity="3" lower="-3.14" upper="3.14"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="left_shoulder">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.025" length="0.05"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (body_width*body_width + body_height1*body_height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (body_height1*body_height1 + body_width*body_width)}" iyz="0.0"
	  izz="${mass / 12.0 * (body_width*body_width + body_width*body_width)}"/>
    </inertial>
  </link>

  <joint name="left_shoulder_joint2" type="revolute">
    <parent link="left_shoulder"/>
    <child link="left_arm"/>
    <origin xyz="0 0 0" rpy="0 ${3.141592/2} 0"/>
	<limit effort="300" velocity="3" lower="-3.14" upper="3.14"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="left_arm">
     <collision>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry>
	    <cylinder radius="0.025" length="0.2"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry>
	    <cylinder radius="0.025" length="0.2"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (body_width*body_width + body_height1*body_height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (body_height1*body_height1 + body_width*body_width)}" iyz="0.0"
	  izz="${mass / 12.0 * (body_width*body_width + body_width*body_width)}"/>
    </inertial>
  </link>

  <joint name="left_elbow_joint" type="revolute">
    <parent link="left_arm"/>
    <child link="left_forearm"/>
    <origin xyz="0 0 0.2" rpy="0 0  0"/>
	<limit effort="300" velocity="3" lower="-3.14" upper="0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="left_forearm">
     <collision>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry>
	    <cylinder radius="0.025" length="0.2"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry>
	    <cylinder radius="0.025" length="0.2"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (body_width*body_width + body_height1*body_height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (body_height1*body_height1 + body_width*body_width)}" iyz="0.0"
	  izz="${mass / 12.0 * (body_width*body_width + body_width*body_width)}"/>
    </inertial>
  </link>

  <joint name="left_hand_joint" type="revolute">
    <parent link="left_forearm"/>
    <child link="left_hand"/>
    <origin xyz="0 0 0.2" rpy="0 0  0"/>
  	<limit effort="300" velocity="3" lower="-3.14" upper="3.14"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="left_hand">
     <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    	  <sphere radius="0.03" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <sphere radius="0.03" />
      </geometry>
      <material name="blue"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (body_width*body_width + body_height1*body_height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (body_height1*body_height1 + body_width*body_width)}" iyz="0.0"
	  izz="${mass / 12.0 * (body_width*body_width + body_width*body_width)}"/>
    </inertial>
  </link>

  
  <!--- Right Arm -->
  <joint name="right_shoulder_joint1" type="revolute">
    <parent link="body_link2"/>
    <child link="right_shoulder"/>
    <origin xyz="0 ${0.1 + 0.025} 0" rpy="0 ${3.141592/2} 0"/>
	<limit effort="300" velocity="3" lower="-3.14" upper="3.14"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="right_shoulder">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.025" length="0.05"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (body_width*body_width + body_height1*body_height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (body_height1*body_height1 + body_width*body_width)}" iyz="0.0"
	  izz="${mass / 12.0 * (body_width*body_width + body_width*body_width)}"/>
    </inertial>
  </link>

  <joint name="right_shoulder_joint2" type="revolute">
    <parent link="right_shoulder"/>
    <child link="right_arm"/>
    <origin xyz="0 0 0" rpy="0 ${3.141592/2} 0"/>
	<limit effort="300" velocity="3" lower="-3.14" upper="3.14"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="right_arm">
     <collision>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry>
	    <cylinder radius="0.025" length="0.2"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry>
	    <cylinder radius="0.025" length="0.2"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${body_height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (body_width*body_width + body_height1*body_height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (body_height1*body_height1 + body_width*body_width)}" iyz="0.0"
	  izz="${mass / 12.0 * (body_width*body_width + body_width*body_width)}"/>
    </inertial>
  </link>

  <joint name="right_elbow_joint" type="revolute">
    <parent link="right_arm"/>
    <child link="right_forearm"/>
    <origin xyz="0 0 0.2" rpy="0 0  0"/>
	<limit effort="300" velocity="3" lower="-3.14" upper="0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="right_forearm">
     <collision>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry>
	    <cylinder radius="0.025" length="0.2"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry>
	    <cylinder radius="0.025" length="0.2"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (body_width*body_width + body_height1*body_height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (body_height1*body_height1 + body_width*body_width)}" iyz="0.0"
	  izz="${mass / 12.0 * (body_width*body_width + body_width*body_width)}"/>
    </inertial>
  </link>

  <joint name="right_hand_joint" type="revolute">
    <parent link="right_forearm"/>
    <child link="right_hand"/>
    <origin xyz="0 0 0.2" rpy="0 0  0"/>
  	<limit effort="300" velocity="3" lower="-3.14" upper="3.14"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>



  <link name="right_hand">
     <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    	  <sphere radius="0.03" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <sphere radius="0.03" />
      </geometry>
      <material name="blue"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (body_width*body_width + body_height1*body_height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (body_height1*body_height1 + body_width*body_width)}" iyz="0.0"
	  izz="${mass / 12.0 * (body_width*body_width + body_width*body_width)}"/>
    </inertial>
  </link>


  <!--transmissions-->
  <!--left-->

  <transmission name="ltran1">
      <type>transmission_interface/SimpleTransmission</type>
	  <joint name="left_shoulder_joint1">
	      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
	  <actuator name="left_motor1">
	      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
  </transmission>

  <transmission name="ltran2">
	  <type>transmission_interface/SimpleTransmission</type>
	  <joint name="left_shoulder_joint2">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
	  <actuator name="left_motor2">
	      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
  </transmission>

  <transmission name="ltran3">
      <type>transmission_interface/SimpleTransmission</type>
	  <joint name="left_elbow_joint">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
	  <actuator name="left_motor3">
	      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
  </transmission>

  <transmission name="ltran4">
      <type>transmission_interface/SimpleTransmission</type>
	  <joint name="left_hand_joint">
	      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
	  <actuator name="left_motor4">
	      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
  </transmission>


  <transmission name="rtran1">
      <type>transmission_interface/SimpleTransmission</type>
	  <joint name="right_shoulder_joint1">
	      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
	  <actuator name="right_motor1">
	      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
  </transmission>

  <transmission name="rtran2">
	  <type>transmission_interface/SimpleTransmission</type>
	      <joint name="right_shoulder_joint2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
	  <actuator name="right_motor2">
	      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
  </transmission>

  <transmission name="rtran3">
      <type>transmission_interface/SimpleTransmission</type>
	  <joint name="right_elbow_joint">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
	  <actuator name="right_motor3">
	      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
  </transmission>

  <transmission name="rtran4">
      <type>transmission_interface/SimpleTransmission</type>
	  <joint name="right_hand_joint">
	      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
	  <actuator name="right_motor4">
	      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
  </transmission>

</robot>
